language: python
cache:
  directories:
    - .venv

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - ls .venv/bin/python &> /dev/null || poetry install

script:
  - make lint-readme
  - make lint
  - make test
