language: python
cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8-dev"
install:
  - pip install poetry
  - poetry install

script:
  - poetry run pytest .

jobs:
  allow_failures:
  - python: '3.8-dev'
