from docutils.nodes import SkipChildren
from sphinx_rst_builder import RstBuilder, RstWriter
from sphinx_rst_builder._writer import RstTranslator


class CustomBuilder(RstBuilder):
    def prepare_writing(self, docnames):
        self.writer = _Writer(self)


class _Writer(RstWriter):
    def translate(self):
        visitor = _Translator(self.document, self.builder)
        self.document.walkabout(visitor)
        self.output = visitor.body
        self.output = f'..\n    AUTOGENERATED DO NOT MODIFY\n{self.output}'


class _Translator(RstTranslator):

    def visit_reference(self, node):
        if len(node.children) == 1 and node.children[0].tagname == 'image':
            img_node = node.children[0]
            self.add_text(f'.. image:: {img_node["uri"]}\n')
            self.add_text(f'   :target: {node["refuri"]}\n')
            raise SkipChildren
        else:
            super().visit_reference(node)
